CIRCUITPY_WIFI_SSID = "ssid_name"
CIRCUITPY_WIFI_PASSWORD = "password"
CIRCUITPY_WEB_INSTANCE_NAME = "GarageOpener-Sensor"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=206
trigger_distance = 20
overclock = "True"
location = "Attic"

sensor1_name = "AHT21"
sensor1_pins = "19,18"
sensor1_correct_temp = "False"

#sensor1 = "BME280"
#sensor1Pins = "18,19,16,17"
#sensor1CorrectTemp = "True"
